---
version: '3.7'
services:
  db:
    image: mysql:5.6
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysqlfordocker}
       MYSQL_DATABASE: ${DB_NAME:-atlasdb}
       MYSQL_USER: ${DB_USERNAME:-atlas}
       MYSQL_PASSWORD: ${DB_PASSWORD:-iamatlas}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: "exit 0"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - default

  atlas:
    build: ./
    image: openmrs/atlas:local
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_NAME: ${DB_NAME:-atlasdb}
      DB_USERNAME: ${DB_USERNAME:-atlas}
      DB_PASSWORD: ${DB_PASSWORD:-iamatlas}
      LDAP_URI: ${LDAP_URI:-ldap://openldap:389}
      LDAP_USER: ${LDAP_USER:-atlas}
      LDAP_PASSWORD: ${LDAP_PASSWORD:-atlas}
      LDAP_USERS_GROUP: ${LDAP_USERS_GROUP:-atlas-users}
      LDAP_ADMIN_GROUP: ${LDAP_ADMIN_GROUP:-atlas-administrators}
      MAIL_HOST: ${MAIL_HOST:-smtp.mandrillapp.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_AUTH: ${MAIL_AUTH:-true}
      MAIL_USER: ${MAIL_USER:-infrastructure@openmrs.org}
      MAIL_PASS: ${MAIL_PASS:-magic}
      GOOGLE_MAPS_JS_API_KEY: ${GOOGLE_MAPS_JS_API_KEY:-XXXXXXXXXXX_XXXXXX-XXXXXXXXXXX-XXXXXXXX}
      ATLAS_LINK_PROTOCOL: ${ATLAS_LINK_PROTOCOL:-http}
      ATLAS_RSS_TITLE: ${ATLAS_RSS_TITLE:-OpenMRS Atlas}
      ATLAS_RSS_DESC: ${ATLAS_RSS_DESC:-Updates to OpenMRS Atlas}
      ATLAS_RSS_LENGTH: ${ATLAS_RSS_LENGTH:-20}
      ATLAS_RSS_IMAGE_URL: ${ATLAS_RSS_IMAGE_URL:-http://localhost:3000/images/red-dot.png}
      ATLAS_RSS_LINK: ${ATLAS_RSS_LINK:-http://localhost}
    ports:
      - 3000:3000
    restart: always
    networks:
      - default
      - ldap
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/markers/"]
volumes:
  mysql-data:

networks:
  default:
  ldap:
    name: ldap-stg_default
    external: true
